/** Iconex 精选图标目录（Figma Community · budggy Iconex） */
const ICON_LIBRARY_ICONEX = [
  { name: 'alarm-clock', cat: 'form', meaning: '闹钟/提醒', scene: '预约提醒、定时任务', source: 'iconex' },
  { name: 'minus', cat: 'action', meaning: '减少', scene: 'Stepper 减、折叠', source: 'iconex' },
  { name: 'play', cat: 'action', meaning: '播放', scene: '音视频、培训', source: 'iconex' },
  { name: 'pause', cat: 'action', meaning: '暂停', scene: '音视频暂停', source: 'iconex' },
  { name: 'stop', cat: 'action', meaning: '停止', scene: '录制结束、终止', source: 'iconex' },
  { name: 'save', cat: 'action', meaning: '保存', scene: '草稿保存、导出', source: 'iconex' },
  { name: 'sale', cat: 'retail', meaning: '促销/特卖', scene: '活动价、秒杀', source: 'iconex' },
  { name: 'rocket', cat: 'action', meaning: '发布/加速', scene: '上线、快捷推广', source: 'iconex' },
  { name: 'expand', cat: 'nav', meaning: '展开', scene: '全屏、展开面板', source: 'iconex' },
  { name: 'collapse', cat: 'nav', meaning: '收起', scene: '退出全屏、折叠', source: 'iconex' },
  { name: 'danger', cat: 'status', meaning: '危险/禁止', scene: '高风险操作警示', source: 'iconex' },
  { name: 'fire', cat: 'status', meaning: '热门', scene: '爆款、热度', source: 'iconex' },
  { name: 'lightning', cat: 'status', meaning: '闪电/极速', scene: '限时、快充', source: 'iconex' },
  { name: 'graph', cat: 'data', meaning: '趋势图', scene: '经营曲线、KPI', source: 'iconex' },
  { name: 'heartbeat', cat: 'data', meaning: '健康/活跃', scene: '会员活跃度', source: 'iconex' },
  { name: 'hide', cat: 'form', meaning: '隐藏内容', scene: '敏感信息、掩码', source: 'iconex' },
  { name: 'microphone', cat: 'comm', meaning: '麦克风', scene: '语音输入、通话', source: 'iconex' },
  { name: 'scanner', cat: 'action', meaning: '扫描器', scene: '扫码枪、识别', source: 'iconex' },
  { name: 'toggle-left', cat: 'form', meaning: '开关（左）', scene: '设置项开关', source: 'iconex' },
  { name: 'toggle-right', cat: 'form', meaning: '开关（右）', scene: '设置项开关', source: 'iconex' },
  { name: 'add-user', cat: 'user', meaning: '添加用户', scene: '邀请成员、拉新', source: 'iconex' },
  { name: 'book', cat: 'file', meaning: '手册/知识', scene: '帮助文档、教程', source: 'iconex' },
  { name: 'browser', cat: 'sys', meaning: '浏览器/H5', scene: '外链、内嵌页', source: 'iconex' },
  { name: 'briefcase', cat: 'biz', meaning: '商务/项目', scene: '企业客户、项目', source: 'iconex' },
  { name: 'category', cat: 'retail', meaning: '分类', scene: '商品类目、筛选', source: 'iconex' },
  { name: 'category-grid', cat: 'retail', meaning: '宫格分类', scene: '品类入口', source: 'iconex' },
  { name: 'category-list', cat: 'retail', meaning: '列表分类', scene: '类目列表', source: 'iconex' },
  { name: 'document-add', cat: 'file', meaning: '新建文档', scene: '新建合同、单据', source: 'iconex' },
  { name: 'document-delete', cat: 'file', meaning: '删除文档', scene: '作废单据', source: 'iconex' },
  { name: 'document-stack', cat: 'file', meaning: '文档叠放', scene: '批量附件', source: 'iconex' },
  { name: 'call-missed', cat: 'comm', meaning: '未接来电', scene: '回访提醒', source: 'iconex' },
  { name: 'call-silent', cat: 'comm', meaning: '静音通话', scene: '勿扰、免打扰', source: 'iconex' },
  { name: 'calling', cat: 'comm', meaning: '呼叫中', scene: '外呼、客服', source: 'iconex' },
  { name: 'info-square', cat: 'status', meaning: '信息（方）', scene: '说明、须知', source: 'iconex' },
  { name: 'time-circle', cat: 'form', meaning: '时间（圆）', scene: '时段选择', source: 'iconex' },
  { name: 'time-square', cat: 'form', meaning: '时间（方）', scene: '排班、班次', source: 'iconex' },
  { name: 'timer', cat: 'form', meaning: '计时器', scene: '倒计时、服务时长', source: 'iconex' },
  { name: 'more-circle', cat: 'action', meaning: '更多（圆）', scene: '卡片菜单', source: 'iconex' },
  { name: 'more-square', cat: 'action', meaning: '更多（方）', scene: '工具栏更多', source: 'iconex' },
  { name: 'palette', cat: 'sys', meaning: '调色/主题', scene: '皮肤、品牌色', source: 'iconex' },
  { name: 'compass', cat: 'nav', meaning: '指南针/发现', scene: '探索、附近', source: 'iconex' },
  { name: 'scale', cat: 'data', meaning: '秤/称重', scene: '体重、计量', source: 'iconex' },
  { name: 'screen', cat: 'sys', meaning: '屏幕/投屏', scene: '大屏、镜像', source: 'iconex' },
  { name: 'bag', cat: 'retail', meaning: '购物袋', scene: '商城、提货', source: 'iconex' },
  { name: 'shopping-bag', cat: 'retail', meaning: '手提袋', scene: '到店自提', source: 'iconex' },
  { name: 'coupon-badge', cat: 'retail', meaning: '优惠券徽章', scene: '领券中心', source: 'iconex' },
  { name: 'coupon-tag', cat: 'retail', meaning: '优惠券标签', scene: '下单抵扣', source: 'iconex' },
  { name: 'chart-alt', cat: 'data', meaning: '图表变体', scene: '报表入口', source: 'iconex' },
  { name: 'chart-trend', cat: 'data', meaning: '趋势图', scene: '同比环比', source: 'iconex' },
  { name: 'lock-open', cat: 'form', meaning: '未锁定', scene: '公开字段', source: 'iconex' },
  { name: 'lock-check', cat: 'form', meaning: '已验证锁', scene: '安全校验通过', source: 'iconex' },
  { name: 'lock-x', cat: 'form', meaning: '锁定失败', scene: '权限不足', source: 'iconex' },
  { name: 'right-circle', cat: 'nav', meaning: '右（圆）', scene: '轮播、下一步', source: 'iconex' },
  { name: 'left-circle', cat: 'nav', meaning: '左（圆）', scene: '上一步', source: 'iconex' },
  { name: 'down-circle', cat: 'nav', meaning: '下（圆）', scene: '展开更多', source: 'iconex' },
  { name: 'up-circle', cat: 'nav', meaning: '上（圆）', scene: '收起', source: 'iconex' },
  { name: 'down-square', cat: 'nav', meaning: '下（方）', scene: '排序降序', source: 'iconex' },
  { name: 'up-square', cat: 'nav', meaning: '上（方）', scene: '排序升序', source: 'iconex' },
  { name: 'right-square', cat: 'nav', meaning: '右（方）', scene: '进入详情', source: 'iconex' },
  { name: 'left-square', cat: 'nav', meaning: '左（方）', scene: '返回', source: 'iconex' },
  { name: 'bell', cat: 'comm', meaning: '铃铛', scene: '通知、提醒', source: 'iconex' },
  { name: 'burger', cat: 'nav', meaning: '汉堡菜单', scene: '侧栏、更多导航', source: 'iconex' },
  { name: 'coffee', cat: 'meiye', meaning: '休闲/茶歇', scene: '生活服务、休息区', source: 'iconex' },
  { name: 'headphones', cat: 'comm', meaning: '耳机/客服', scene: '在线客服、音频', source: 'iconex' },
  { name: 'paperclip', cat: 'file', meaning: '回形针', scene: '附件、关联', source: 'iconex' },
  { name: 'cloud-download', cat: 'action', meaning: '云下载', scene: '云端拉取', source: 'iconex' },
  { name: 'cloud-upload-alt', cat: 'action', meaning: '云上传', scene: '备份同步', source: 'iconex' },
  { name: 'download-alt', cat: 'action', meaning: '下载变体', scene: '导出文件', source: 'iconex' },
  { name: 'link-chain', cat: 'file', meaning: '链接', scene: '复制链接、关联', source: 'iconex' },
  { name: 'link-external-alt', cat: 'file', meaning: '外链', scene: '打开 H5', source: 'iconex' },
  { name: 'message-circle-alt', cat: 'comm', meaning: '消息（圆）', scene: '会话、IM', source: 'iconex' },
  { name: 'edit-alt', cat: 'action', meaning: '编辑变体', scene: '备注、批改', source: 'iconex' },
  { name: 'chart-pie-alt', cat: 'data', meaning: '饼图变体', scene: '占比分布', source: 'iconex' },
  { name: 'coins', cat: 'order', meaning: '硬币/积分', scene: '积分商城、返利', source: 'iconex' },
  { name: 'credit-card-alt', cat: 'order', meaning: '银行卡变体', scene: '绑卡、收款', source: 'iconex' },
  { name: 'box-package', cat: 'order', meaning: '包裹', scene: '发货、库存', source: 'iconex' },
  { name: 'box-open', cat: 'order', meaning: '开箱', scene: '收货、拆包', source: 'iconex' },
  { name: 'alarm-clock-filled', cat: 'filled', meaning: '闹钟（面性）', scene: '强提醒', source: 'iconex' },
  { name: 'play-filled-alt', cat: 'filled', meaning: '播放（面性）', scene: '视频强调', source: 'iconex' },
  { name: 'pause-filled-alt', cat: 'filled', meaning: '暂停（面性）', scene: '播放控制', source: 'iconex' },
  { name: 'stop-filled-alt', cat: 'filled', meaning: '停止（面性）', scene: '终止操作', source: 'iconex' },
  { name: 'sale-filled', cat: 'filled', meaning: '促销（面性）', scene: '活动 Tab', source: 'iconex' },
  { name: 'rocket-filled', cat: 'filled', meaning: '发布（面性）', scene: '上线强调', source: 'iconex' },
  { name: 'scanner-filled', cat: 'filled', meaning: '扫描（面性）', scene: '扫码入口', source: 'iconex' },
  { name: 'microphone-filled', cat: 'filled', meaning: '麦克风（面性）', scene: '语音消息', source: 'iconex' },
  { name: 'graph-filled', cat: 'filled', meaning: '趋势（面性）', scene: '数据 Tab', source: 'iconex' },
  { name: 'heartbeat-filled', cat: 'filled', meaning: '活跃（面性）', scene: '健康度', source: 'iconex' },
  { name: 'expand-filled', cat: 'filled', meaning: '展开（面性）', scene: '全屏态', source: 'iconex' },
  { name: 'collapse-filled', cat: 'filled', meaning: '收起（面性）', scene: '退出全屏', source: 'iconex' },
  { name: 'danger-filled', cat: 'filled', meaning: '危险（面性）', scene: '删除确认', source: 'iconex' },
  { name: 'fire-filled', cat: 'filled', meaning: '热门（面性）', scene: '爆款标签', source: 'iconex' },
  { name: 'sale-tag-filled', cat: 'filled', meaning: '券标（面性）', scene: '领券', source: 'iconex' },
  { name: 'bag-filled', cat: 'filled', meaning: '购物袋（面性）', scene: '商城 Tab', source: 'iconex' },
  { name: 'category-filled', cat: 'filled', meaning: '分类（面性）', scene: '类目选中', source: 'iconex' },
  { name: 'document-add-filled', cat: 'filled', meaning: '新建文档（面性）', scene: '开单强调', source: 'iconex' },
  { name: 'document-delete-filled', cat: 'filled', meaning: '删文档（面性）', scene: '作废', source: 'iconex' },
  { name: 'calling-filled', cat: 'filled', meaning: '呼叫（面性）', scene: '外呼中', source: 'iconex' },
  { name: 'browser-filled', cat: 'filled', meaning: '浏览器（面性）', scene: 'H5 入口', source: 'iconex' },
  { name: 'book-filled', cat: 'filled', meaning: '手册（面性）', scene: '培训', source: 'iconex' },
  { name: 'save-filled', cat: 'filled', meaning: '保存（面性）', scene: '提交保存', source: 'iconex' },
  { name: 'screen-filled', cat: 'filled', meaning: '屏幕（面性）', scene: '投屏', source: 'iconex' },
  { name: 'scale-filled', cat: 'filled', meaning: '秤（面性）', scene: '称重', source: 'iconex' },
  { name: 'compass-filled', cat: 'filled', meaning: '发现（面性）', scene: '探索 Tab', source: 'iconex' },
  { name: 'briefcase-filled', cat: 'filled', meaning: '商务（面性）', scene: 'B 端入口', source: 'iconex' },
  { name: 'palette-filled', cat: 'filled', meaning: '主题（面性）', scene: '换肤', source: 'iconex' },
  { name: 'timer-filled', cat: 'filled', meaning: '计时（面性）', scene: '服务倒计时', source: 'iconex' },
  { name: 'toggle-left-filled', cat: 'filled', meaning: '开关（面性）', scene: '设置开启', source: 'iconex' },
  { name: 'more-square-filled', cat: 'filled', meaning: '更多（面性）', scene: '工具栏', source: 'iconex' },
  { name: 'chart-filled-alt', cat: 'filled', meaning: '图表（面性）', scene: '报表 Tab', source: 'iconex' },
  { name: 'chart-trend-filled', cat: 'filled', meaning: '趋势（面性）', scene: '业绩', source: 'iconex' },
  { name: 'coins-filled', cat: 'filled', meaning: '积分（面性）', scene: '积分商城', source: 'iconex' },
  { name: 'coffee-filled', cat: 'filled', meaning: '茶歇（面性）', scene: '生活服务', source: 'iconex' },
  { name: 'headphones-filled', cat: 'filled', meaning: '客服（面性）', scene: '在线客服', source: 'iconex' },
  { name: 'burger-filled', cat: 'filled', meaning: '菜单（面性）', scene: '侧栏', source: 'iconex' },
  { name: 'box-filled', cat: 'filled', meaning: '包裹（面性）', scene: '物流', source: 'iconex' }
];
